/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LeaderRouteImport } from './routes/leader'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MapCodeRouteImport } from './routes/map.$code'
import { Route as AdminTokenRouteImport } from './routes/admin.$token'

const LeaderRoute = LeaderRouteImport.update({
  id: '/leader',
  path: '/leader',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MapCodeRoute = MapCodeRouteImport.update({
  id: '/map/$code',
  path: '/map/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTokenRoute = AdminTokenRouteImport.update({
  id: '/admin/$token',
  path: '/admin/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/leader': typeof LeaderRoute
  '/admin/$token': typeof AdminTokenRoute
  '/map/$code': typeof MapCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/leader': typeof LeaderRoute
  '/admin/$token': typeof AdminTokenRoute
  '/map/$code': typeof MapCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/leader': typeof LeaderRoute
  '/admin/$token': typeof AdminTokenRoute
  '/map/$code': typeof MapCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/leader' | '/admin/$token' | '/map/$code'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/leader' | '/admin/$token' | '/map/$code'
  id: '__root__' | '/' | '/leader' | '/admin/$token' | '/map/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LeaderRoute: typeof LeaderRoute
  AdminTokenRoute: typeof AdminTokenRoute
  MapCodeRoute: typeof MapCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/leader': {
      id: '/leader'
      path: '/leader'
      fullPath: '/leader'
      preLoaderRoute: typeof LeaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map/$code': {
      id: '/map/$code'
      path: '/map/$code'
      fullPath: '/map/$code'
      preLoaderRoute: typeof MapCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$token': {
      id: '/admin/$token'
      path: '/admin/$token'
      fullPath: '/admin/$token'
      preLoaderRoute: typeof AdminTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LeaderRoute: LeaderRoute,
  AdminTokenRoute: AdminTokenRoute,
  MapCodeRoute: MapCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
